### ISSUE TITLE
"Profile" is twice in the list

### ISSUE THREAD

**Issue by Bouh** [GDevelopApp/GDevelop-documentation#160]
![image](https://github.com/GDevelopApp/GDevelop-documentation/assets/1670670/9bdffd12-b180-4302-b320-4c2ca373404d)

**Comment by ClementPasteau** [comment]
I think this is fixed now
![image](https://github.com/GDevelopApp/GDevelop-documentation/assets/4895034/a1428288-0dc8-48ac-bfc8-599a7386c2e1)
